### ISSUE TITLE
Setting a default type for a trait object

### ISSUE THREAD

**Issue by ISibboI** [dtolnay/typetag#3]
Is it possible to set one of the trait impls as the default impl, that is chosen when no type is given?

Say I have a trait `T`, and multiple types `A`, `B`, `C`. I would like to be able to set `A` as the default.
So I would for example write:

```rust
#[typetag::serde(default)]
impl T for A;
#[typetag::serde]
impl T for B;
#[typetag::serde]
impl T for C;
```

This would be a really nice feature for me, and I think in general this crate could benefit from that.

**Comment by dtolnay** [comment]
I would accept a PR to implement this!

**Comment by ISibboI** [comment]
I would be happy to implement this, since this is a really useful crate. But sadly my knowledge of macros and serde is not enough to understand the code of this crate.

**Comment by agirardeau** [comment]
Considering implementing this. Are you opinionated about whether `default` should be specified on the trait or on the default implementation? Trait feels cleaner to me, but it does affect the logic determining internal/adjacent/external representation a bit. There would now be five options for parameters:

```
#[typetag::serde]  // -> external
#[typetag::serde(type = "type")]  // -> internal
#[typetag::serde(type = "type", default = "default")]  // -> internal
#[typetag::serde(type = "type", content = "content")]  // -> adjacent
#[typetag::serde(type = "type", content = "content", default = "default")]  // -> adjacent
```

Does that seem like the right way to implement this?

**Comment by agirardeau** [comment]
Started PR #55 for this. One question is whether to serialize the type field when it's the default value. Not serializing it breaks non-self describing formats like bincode.

I think there are three options:

1. Always serialize the type field, even when it's the default value
2. Add another flag to the proc macro to control whether the type field is serialized if it's the default value, noting in the docs that this breaks non-self describing formats
3. Serialize the type field if the Serializer's `is_human_readable()` method returns false. This would probably work for most formats, but would break if there's ever a non-self describing format that is human readable

Option (1) seems the best to me for an initial implementation, I'll update the PR to do that unless I hear otherwise.

**Comment by ISibboI** [comment]
Thank you a lot for implementing this! I think option 1 is the right choice to start out with, since it is better to be explicit. If someone wants the optimisation, they can make a another issue. 

I think if we want this optimisation, then someone should make sure that it does not add unexpected side effects like the ones you describe. After all, this is a very abstract crate with a wide audience, so having it behave "as expected" is an important goal.
